- py manage.py makemigrations
    SystemCheckError: System check identified some issues:

    ERRORS:
    auth.User.groups: (fields.E304) Reverse accessor 'Group.user_set' for 'auth.User.groups' clashes with reverse accessor for 'userauths.User.groups'.
            HINT: Add or change a related_name argument to the definition for 'auth.User.groups' or 'userauths.User.groups'.
    auth.User.user_permissions: (fields.E304) Reverse accessor 'Permission.user_set' for 'auth.User.user_permissions' clashes with reverse accessor for 'userauths.User.user_permissions'.
            HINT: Add or change a related_name argument to the definition for 'auth.User.user_permissions' or 'userauths.User.user_permissions'.
    userauths.User.groups: (fields.E304) Reverse accessor 'Group.user_set' for 'userauths.User.groups' clashes with reverse accessor for 'auth.User.groups'.
            HINT: Add or change a related_name argument to the definition for 'userauths.User.groups' or 'auth.User.groups'.
    userauths.User.user_permissions: (fields.E304) Reverse accessor 'Permission.user_set' for 'userauths.User.user_permissions' clashes with reverse accessor for 'auth.User.user_permissions'.
            HINT: Add or change a related_name argument to the definition for 'userauths.User.user_permissions' or 'auth.User.user_permissions'.

- Solution:
* Due to extending of abstract user Model thiserror arise.*
    - settings.py file
        # User Model Auth
        AUTH_USER_MODEL = 'userauths.User'